# -*- coding: utf-8 -*-
"""Forward Chaining_Status Toko

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rBOEK0cYWpkAv89IV6oRt3PascPk4WrH
"""

# Upload dataset
from google.colab import files
files.upload()

# Membaca dataset
import pandas as pd
df = pd.read_csv("customer_shopping_data_aftercleaning.csv")

# Konversi Tanggal dan Ambil Tahun
df['invoice_date'] = pd.to_datetime(df['invoice_date'])

df['year'] = df['invoice_date'].dt.year

df[['invoice_date','year']].head()

# Ambil Data Tahun 2021 dan 2022
df_filtered = df[df['year'].isin([2021, 2022])]

print(df_filtered['year'].unique())

# Hitung Total Penjualan per Toko per Tahun
sales_per_year = (
    df.groupby(['shopping_mall','year'])['total_sales']
      .sum()
      .reset_index()
)

sales_per_year.head()

# Pisahkan Penjualan 2021 dan 2022
sales_pivot = sales_per_year.pivot(
    index='shopping_mall',
    columns='year',
    values='total_sales'
).reset_index()

sales_pivot

# Hitung Persentase Pertumbuhan
sales_pivot['growth_percent'] = (
    (sales_pivot[2022] - sales_pivot[2021])
    / sales_pivot[2021]
) * 100

"""**ATURAN FORWARD CHAINING**

Rule 1:
IF growth > 15%
THEN status = Naik

Rule 2:
IF growth < 0%
THEN status = Turun

Rule 3:
IF 0% <= growth <= 15%
THEN status = Stagnan
"""

# Aturan Forward Chaining
def forward_chaining_status(growth):

    # Tahun pertama tidak memiliki data pembanding
    if pd.isna(growth):
        return "Data Awal"

    # Rule 1
    if growth > 15:
        return "Naik"

    # Rule 2
    if growth < 0:
        return "Turun"

    # Rule 3
    return "Stagnan"

# Jalankan Aturan
sales_pivot['status_toko'] = (
    sales_pivot['growth_percent']
    .apply(forward_chaining_status)
)

# Tampilkan Status Semua Toko
hasil_fc = sales_pivot[
    ['shopping_mall',
     2021,
     2022,
     'growth_percent',
     'status_toko']
]

hasil_fc

# Hitung Jumlah Status
hasil_fc['status_toko'].value_counts()

# Simpan hasil ke csv
hasil_fc.to_csv(
    "hasil_forward_chaining.csv",
    index=False
)